name: "Feature Request: flow"
description: Suggest a feature for the flow plugin
labels: ["flow", "enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
    validations:
      required: false
