name: "Bug Report: statuskit"
description: Report a bug in the statuskit package
labels: ["statuskit", "bug"]
body:
  - type: input
    id: version
    attributes:
      label: Statuskit Version
      description: What version of statuskit are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os-python
    attributes:
      label: OS / Python Version
      description: Your operating system and Python version
      placeholder: "macOS 14.0, Python 3.12"
    validations:
      required: true

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version
      description: What version of Claude Code CLI are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run statuskit with '...'
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
