name: 'Telegram Notify'
description: 'Send CI/CD status notifications to Telegram'

inputs:
  status:
    description: 'started | success | failure | cancelled'
    required: true
  event-type:
    description: 'pr | push | release'
    required: true
  title:
    description: 'Message title (e.g., PR #42: Add feature)'
    required: true
  event-url:
    description: 'URL to PR/commit/release'
    required: true
  message:
    description: 'Additional message text'
    required: false
    default: ''
  collect-failed-jobs:
    description: 'Fetch failed jobs list via GitHub API'
    required: false
    default: 'false'
  token:
    description: 'Telegram bot token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Telegram notification
      shell: bash
      env:
        STATUS: ${{ inputs.status }}
        EVENT_TYPE: ${{ inputs.event-type }}
        TITLE: ${{ inputs.title }}
        EVENT_URL: ${{ inputs.event-url }}
        MESSAGE: ${{ inputs.message }}
        COLLECT_FAILED_JOBS: ${{ inputs.collect-failed-jobs }}
        TELEGRAM_TOKEN: ${{ inputs.token }}
        TELEGRAM_CHAT_ID: ${{ inputs.chat-id }}
      run: |
        set -euo pipefail

        # 1. Icon by status
        case "$STATUS" in
          started)   ICON="🚀" ;;
          success)   ICON="✅" ;;
          failure)   ICON="❌" ;;
          cancelled) ICON="⛔" ;;
          *)         ICON="❓" ;;
        esac

        # 2. Header
        HEADER="${ICON} ${GITHUB_REPOSITORY} | ${TITLE}"

        # 3. Links
        RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        case "$EVENT_TYPE" in
          pr)      LINK_TEXT="View PR" ;;
          push)    LINK_TEXT="View commit" ;;
          release) LINK_TEXT="View release" ;;
          *)       LINK_TEXT="View" ;;
        esac
        LINKS="[${LINK_TEXT}](${EVENT_URL}) | [View run](${RUN_URL})"

        # 4. Failed jobs summary (if enabled)
        FAILED_SUMMARY=""
        if [ "$COLLECT_FAILED_JOBS" = "true" ]; then
          FAILED_SUMMARY=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs" \
            | jq -r '.jobs[] | select(.conclusion == "failure") | "  • \(.name)"' \
            | head -20) || true
        fi

        # 5. Build message
        TEXT="${HEADER}"
        [ -n "$MESSAGE" ] && TEXT="${TEXT}
        ${MESSAGE}"
        [ -n "$FAILED_SUMMARY" ] && TEXT="${TEXT}
        ${FAILED_SUMMARY}"
        TEXT="${TEXT}
        ${LINKS}"

        # 6. Send to Telegram
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="$TEXT" \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview="true"
